### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by ltarquinio** [kanryu/quick-csv#1]
Hi dear,

I would know if you will update the tool with error reportings... For example: "This line can't be inserted cause...".

Thank you and have a nice 2021!

**Comment by kanryu** [comment]
Thank you for your interest in this library. However, your report is incomplete and I can't investigate from your text alone.

Perhaps you're getting an insert error due to duplicate primary keys. This library assumes that the table to be input by CSV has a relatively simple table schema. It may not behave as you expected.

Stop the import process by this library in the middle and observe carefully whether the data of the created temporary table can really be inserted into the target table.

**Comment by ltarquinio** [comment]
Hello, 
Thanks for the answer. I think that what i told you wasn't too explained and sorry for it.
I'll try again.
This topic is not an Error Reporting but the function that I wish in this library. 

That is: 

I am importing an new csv to my database, ok? And with it, i would like and know if can you put a new function that returns the line that wasn't inserted.

Is it possible?

Thank you;
